version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog_app_image_flask
    container_name: flask_app
    ports:
      - "5010:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"

